#!/bin/bash
#About this script information

clear
echo -e "------------------------------------------------------"
echo -e ""
echo -e "-------Script Auto Install SSH & OpenVPN Ver1.0 ------" 
echo -e ""
echo -e "------------------------------------------------------"
echo -e ""
echo -e "1. Suitable for Linux Debian 9 32 bit & 64 bit"
echo -e "2. Suitable for VPS with KVM and VMWare virtualization"
echo -e "3. Use for SSH & VPN Business"
echo -e ""
echo -e ""
echo -e "######################################################"
echo -e "#                                                    #"
echo -e "#               --ORIGINAL SCRIPT BY--               #"
echo -e "#                   *SHVPNMalaysia*                  #"
echo -e "#                   *Khairul SHVPN*                  #"
echo -e "#                                                    #"
echo -e "######################################################"
echo -e ""
echo -e "------------------------------------------------------"
echo -e "Whatsapp = +601119800265"
echo -e "Telegram = http://t.me/kaselurk"
echo -e "FB       = https://www.facebook.com/SHVPNMalaysia"
echo -e "Website  = http://shvpnpower.cf"
echo -e ""
echo -e "------------------------------------------------------"
echo -e "!!!!!!!!!!SHVPN - YOUR INTERNET SPEED EXPERT!!!!!!!!!!"
echo -e "------------------------------------------------------"
echo -e ""
