#!/bin/bash
#Menu

echo -e "* Menu         : Senarai menu yang boleh digunakan"
echo -e "* NewUser      : Membuat Akaun SSH Baru"
echo -e "* NewUserSSL   : Membuat Akaun SSL Baru"
echo -e "* Trial        : Membuat Akaun Trial"
echo -e "* TrialSSL     : Membuat Akaun Trial SSL"
echo -e "* UserOVPN     : Membuat Akaun OpenVPN"
echo -e "* Remove       : Membuang Akaun Pengguna SSH"
echo -e "* Check        : Semak Pengguna Yang Sedang Login"
echo -e "* User         : Semak Senarai Pengguna SSH"
echo -e "* ResServ      : Restart Service Dropbear, Webmin,"
echo -e "                 Squid3, OpenVPN dan SSH"
echo -e "* Reboot       : Reboot VPS Anda"
echo -e "* Speedtest    : Speedtest VPS Anda"
echo -e "* Info         : Memaparkan segala info tentang VPS Anda"
echo -e "* About        : Informasi tentang script auto install"
echo -e "* exit         : keluar dari Putty/Connectbot/"
echo -e "                 JuiceSSH"
echo -e ""
